---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  roles_path: "../roles"
  
platforms:
  - name: centos-7
    driver_config:
      provision_command: 
        - yum install epel-release -y
        - yum makecache
        - yum -y install ansible libselinux-python git
        - yum install -y curl tree git yum-utils bind-utils jq openssh-clients rsync python-setuptools python-pip pyYAML python-jinja2 python-httplib2 unzip
        - pip install --upgrade pip
        - pip install ansible marathon pexpect dnspython pyvmomi pysphere bigsuds jsonschema requests netaddr dnspython boto virtualenv
      image: ansible/centos7-ansible:stable
      platform: centos    


suites:
  - name: default
    verifier:
      patterns:
        - roles/oracle-jdk8/test/integration/default/serverspec/default_spec.rb
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
